#! /bin/sh

# Check spelling of code.

# Recognize and skip backslash sequences in strings.
# Ignore hexadecimal numbers.
# Ignore SHA-1 hashes.
# Split CamelCase words.

export LC_ALL=en_US.UTF-8

sed '/"/s/\\[nst]/ /g' "$@" | \
sed 's/\<0[xX][0-9A-Fa-f]\+U\?L\?L\?\>/ /g' | \
sed 's/\<[0-9a-f]\{40\}\>/ /g' | \
sed 's/\(.\)\([A-Z][a-z]\+\)/\1 \2/g;s/\([a-z0-9]\)\([A-Z]\)/\1 \2/g' | \
aspell --lang=en_US list | \
sort -u
