#! /bin/sh

exec /opt/homebrew/bin/qemu-system-aarch64 \
	-machine virt,gic-version=3 -accel hvf -m 32768 -cpu host -smp cpus=12,sockets=1,cores=12,threads=1 \
	-nodefaults -nographic -vga none -audio none \
	-device virtio-net-pci,netdev=net0 -netdev user,id=net0,hostfwd=tcp::2022-:22 \
	-device virtio-rng-pci \
	-device virtio-blk-pci,drive=VDA0,bootindex=0 \
	-drive if=pflash,format=raw,file.filename=/opt/homebrew/share/qemu/edk2-aarch64-code.fd,file.locking=off,readonly=on \
	-drive if=pflash,file.filename=/usr/local/vm/efi_vars.fd \
	-drive if=none,media=disk,id=VDA0,file.filename=/usr/local/vm/n1.qcow2,discard=unmap,detect-zeroes=unmap \
	>/usr/local/vm/log.txt 2>&1
